### PR TITLE
collapses overlay submodules into main repo

### PR DESCRIPTION
**Pull request by kareem613**
This brings in all the plugin submodules into the main repo as discussed for Issue #36 .
Full commit history is maintained and no plugin files were modified at all. 
You'll notice a lot of commits. That's just the history of the plugins. I didn't make any changes to them.

### CODE REVIEW

**Comment by MerlinCooper** [comment]
Looks good to me - but do you think we do still need the .sln files for the overlay plugin's. 

From my understanding it should be sufficient to have on solution which contains the projects .csproj files and the solution was just there because the of referencing it via a submodule.

**Comment by kareem613** [comment]
> Looks good to me - but do you think we do still need the .sln files for the overlay plugin's.
> 
> From my understanding it should be sufficient to have on solution which contains the projects .csproj files and the solution was just there because the of referencing it via a submodule.

Good point. I'll remove those and update the PR.

**Comment by MerlinCooper** [comment]
We can do that in the pull request within here - can't we?

**Comment by MerlinCooper** [comment]
would you mind double-checking whether I found all .sln files?

**Comment by kareem613** [comment]
There's more to it. Nuspec files, some other stuff.
Easier locally.

Do need any of those package.cmd files in the tools folders? Those aren't for azure pipelines right?

**Comment by MerlinCooper** [comment]
> Do need any of those package.cmd files in the tools folders? Those aren't for azure pipelines right?

Pretty sure that those are not for azure pipeline. Do think hat this cmd files have been used by Vipoo to deploy the package/files. But that doesn't work anymore. There are more code(e.g. AWS) which is no longer needed and is just throwing exceptions whenever the application is started. 

We can either clean the solution in one step - or do it step after step. Doing smaller steps might be easier to roll-back if something goes wrong. 

The only file added by azure pipeline is azure-pipelines.yml.

**Comment by MerlinCooper** [comment]
By the way the NuSpec files are something on it's own. Don't know how often I did upgrade some NuGet packages in the past. But somehow I did not get that merged / commited to the master branch. But that might be my limited experience with GitHub.

**Comment by MerlinCooper** [comment]
I would suggest I do merge the PR as it is and you can further clean-up the project file from there. 

By the way: Do you think I would be able to cherry-pick the changes you made into the branch "Fast_Video_Recording_With_OBS"?

**Comment by kareem613** [comment]
Agreed. Merge what's there now. I'll do the next cleanup in another branch.
After you merge I'll take a look at merging that up to your obs branch. 

We should get on a discord server or something for these conversations.

**Comment by kareem613** [comment]
@MerlinCooper 
I took a quick look at merging all this with the obs branch. Only conflicts are in the .gitmodules and the sln/csproj files. Should be easy once you merge this PR.

**Pull request merged**
