### PR TITLE
merges master up to the Fast OBS branch. 

### PR DESCRIPTION
**Pull request by kareem613**
This merge was a bit painful because of the submodule removal. We should be good moving forward from here. 
Please merge this before doing more work on the Fast branch to avoid more merge issues. 
This won't be a problem moving forward with the submodules taken care of.

### CODE REVIEW

**Comment by MerlinCooper** [comment]
Thanks for going through that but are you sure that the project still compiles? Did checkout the master branch and tried to build the sources but had a lot of failures.
Are you using VS2017 or VS2019?

P.S.: my preferences is to finish up the alpha version before re-doing this messy solution. I even do think about just moving the plugin project into a separate solution.

**Comment by kareem613** [comment]
Yes. Everything builds fine. 
Let me do a fresh checkout from scratch and confirm. Everything should be set the .net 4.7.2. If there's any project that isn't, it'll cause build issues.
I'm using VS 2017 but I also have 2019 community. What are you using?

The plugin projects are simple enough. I don't think it's worth pulling them out. Not yet at least.

**Comment by MerlinCooper** [comment]
I'm using VS2017 as well - weird that I did pull a fresh clone and the master branch did no longer compile.

**Comment by kareem613** [comment]
I think I see why. The Tests project in the iracingSDK repo isn't 4.7.2.
It needs to be updated. I guess it wasn't when it the SDK was updated to
4.7.2.

**Comment by MerlinCooper** [comment]
This one doesn't even pass the check by azure pipeline - it's causing 18 errors mostly due to assembl references to the iRacing SDK missing. Was before down to 2 failures because the linked submodules did not have the values for the new keystrokes to pause the replay in

**Comment by kareem613** [comment]
If I unload the iRacingSDK.Net.Tests project everything builds fine. Azure pipelines build failure are all due that project not being 4.7.2. 
You own the SDK repo right? Can you make that update? I can update the PR to the new head once you commit that change in the SDK repo.

**Comment by MerlinCooper** [comment]
By the way I recommend upgrading the YAML Nuget to version 5.3.1 - some code in the plugins is still using versions before 3.1.1 and that creates vulnerability reports.

Do not recommend to upgrade to 8.1.2 at the moment - did that one time and afterwards the app did no longer recognize the start of iRacing (let's keep that for later).

P.S..:  For the replayscript I'm planing to use JSON anyway because much easier to read if required. At the moment the replaysript is written in YAML and JSON format

**Comment by MerlinCooper** [comment]
> 
> 
> If I unload the iRacingSDK.Net.Tests project everything builds fine. Azure pipelines build failure are all due that project not being 4.7.2.
> You own the SDK repo right? Can you make that update? I can update the PR to the new head once you commit that change in the SDK repo.

Updated the iRacingSDK with https://github.com/MerlinCooper/iRacingSDK.Net/commit/7f651eeed05e81b5f2a3899d04f9ded7d1079493

Did a new version of the NuGet 1.0.0.43 as well - although nothing should have changed in this part of the solution.

Curiously the project wasn't in the solution file anymore - because at some point of time I removed it due to not compiling anymore after updating to YAML 5.3.1. Did not miss the project so far because it doesn't really do someting - anyway updated the code thus it compiles.

**Comment by MerlinCooper** [comment]
Had another look on the "assembly reference missing" errors we are facing during building the project. 

https://github.com/dotnet/standard/issues/481

Looks like there is a known bug with .NET 4.7.1 framework which can cause this failures when using package.config files instead of package-references (which was introduced with VS2017).

Will try to apply the workaround for the iRacingSDK.NET project and see wheather this help. If it works we might have to migrate the iRacingReplayDirector to packagereference as well. But that would mean that VS2017 or newer is required to compile afterwards.

**Comment by MerlinCooper** [comment]
Can confirm that migrating to packagereferences did resolve the issue for the iRacingSDK.NET project not being able to compile with azure pipelines sometimes. 

Will do the same on the master branch for the iRacingReplayDirector.

**Comment by kareem613** [comment]
I wonder why it's only an issue with the Tests project. Odd. 
Glad you worked it out. 
BTW. I don't mind if VS2017 or even Community 2019 is required. It's not unreasonable. Would make like easier keeping up to date overall.

**Comment by MerlinCooper** [comment]
Will merge just the changed sources into the master branch and make sure that "master" compiles under all circumstances

**Comment by MerlinCooper** [comment]
@kareem613 That wasn't easy. After merging everything into the master branch it took me 2 days to get it working / compiling with AzureDev as well. 

But now everything compiles and is up-to-date to .NET 4.7.2 and uses PackageReferences.

**Comment by kareem613** [comment]
Ok. Great. Only tough (super tough) because of the submodule removal and .net version mismatched. Looks like the hard stuff is behind us.

**Pull request closed without merging**
